---
- name: sysctl
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv4.conf.all.forwarding
    - net.ipv4.tcp_fastopen

