---
- name: nfs
  mount: 
    path: /opt/kube-configs
    src: 172.16.0.1:/mnt/nfs
    fstype: nfs
    opts: rw,user
    state: mounted
- name: swap
  shell: swapoff -a
- name: docker
  systemd:
    name: docker
    state: started
    enabled: yes
- name: hold_pkg
  shell: apt-mark hold kubelet kubeadm kubectl
- name: hold_pkg
  systemd:
    name: kubelet
    state: started
    enabled: yes
- name: flannel
  shell: kubectl apply -f /opt/kube-configs/flannel.yaml
- name: ntp
  copy: 
    src: files/ntp.conf
    dest: /etc/ntp.conf
- name: ntp
  systemd:
    name: ntp
    state: restarted
    enabled: yes
- name: gluster
  systemd:
    name: 
- name: gluster
  systemd:
    name: glusterd
    state: started
    enabled: yes
- name: helm-rbac
  become_user: comrade
  shell: kubectl apply -f /opt/kube-configs/helm-rbac.yaml
- name: helm_init
  command: helm init --service-account tiller  --history-max 100
- name: ingress
  shell: helm install /opt/kube-configs/ingress/deployments/helm-chart/
  
