---
- name: swap
  shell: swapoff -a
- name: docker
  systemd:
    name: docker
    state: started
    enabled: yes
- name: hold_pkg
  shell: apt-mark hold kubelet kubeadm kubectl
- name: hold_pkg
  systemd:
    name: kubelet
    state: started
    enabled: yes
- name: ntp
  copy:
    src: files/ntp.conf
    dest: /etc/ntp.conf
- name: ntp
  systemd:
    name: ntp
    state: restarted
    enabled: yes
