---
- name: disable swap
  lineinfile:
    path: /etc/fstab
    regexp: '^/swap*'
    line: '#/swap.img'
  notify: swap
  tags: swap
- name: sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo ALL='
    line: '%sudo   ALL=(ALL:ALL)   NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
  tags: sudo
- name: remove firewall
  apt:
    name: ufw
    state: absent
- name: add key for docker repository
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: k8s
- name: add repository for docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes
  tags: k8s
- name: add key for kubernetes repository
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags: k8s
- name: add repository for kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes
  tags: k8s
- name: install container runtime
  apt: 
    name: docker-ce=18.06.1~ce~3-0~ubuntu 
    state: installed
  tags: docker
- name: docker configuration
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  notify: docker
  tags: docker
- name: install packages
  apt:
    name: "{{ k8s_pkg }}"
  notify: hold_pkg
  tags: k8s
- name: cluster init
  shell: kubeadm init --apiserver-advertise-address=172.16.0.2 --pod-network-cidr=10.244.0.0/16
  register: kube_init
  tags: k8s_init
- name: copy output to file
  local_action: copy content= "{{ kube_init }}" dest=/opt/kube-configs/kube_init 
- name: kubectl configuration
  shell: mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown comrade:comrade $HOME/.kube/config
  tags: k8s_init
- name: download flannel
  shell: wget  https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml -O /opt/kube-configs/flannel.yaml
  notify: flannel
  tags: flannel
