---
- name: install nfs
  apt: 
    name: nfs-common
    state: present
- name: create dir
  file:
    path: /opt/kube-configs
    owner: comrade
    group: comrade
    state: directory
    mode: '700'
- name: create record in fstab
  lineinfile:
    path: /etc/fstab
    insertafter: 'EOF'
    line: '172.16.0.1:/mnt/nfs /opt/kube-configs        nfs     user,rw 0 0'
  notify: nfs
  tags: nfs
- name: disable swap
  lineinfile:
    path: /etc/fstab
    regexp: '^/swap*'
    line: '#/swap.img'
  tags: swap
- name: sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%SUDO ALL='
    line: '%sudo   ALL=(ALL:ALL)   NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
  tags: sudo
- name: remove firewall
  apt:
    name: ufw
    state: absent
- name: include sysctl
  include: ../controller/tasks/sysctl.yaml
  tags: sysctl
