---
- name: install nfs
  apt: 
    name: nfs-common
    state: present
- name: create dir
  file:
    path: /opt/kube-configs
    owner: comrade
    group: comrade
    state: directory
    mode: '700'
- name: create record in fstab
  lineinfile:
    path: /etc/fstab
    insertafter: 'EOF'
    line: '172.16.0.1:/mnt/nfs /opt/kube-configs        nfs     user,rw 0 0'
  notify: nfs
  tags: nfs
- name: include sysctl
  include: ../controller/tasks/sysctl.yaml
  tags: sysctl
- name: include common
  include: common.yaml
- name: include kubernetes init
  include: kube_init.yaml
  tags: k8s_init
- name: rbac configuration for helm
  copy:
    src: files/helm-rbac.yaml
    dest: /opt/kube-configs/helm-rbac.yaml
  tags: helm
  notify: helm-rbac
- name: create directory for helm
  file:
    path: /opt/helm
    owner: comrade
    group: comrade
    state: directory
  tags: helm
- name: download helm
  unarchive: 
    src: https://get.helm.sh/helm-v2.14.2-linux-amd64.tar.gz
    dest: /opt/helm
    remote_src: yes
  tags: helm
- name: move helm binary
  command: mv /opt/helm/linux-amd64/helm /usr/local/bin/helm
  notify: helm_init
  tags: helm_init

